// Regenerate src/jit_js.h from wasmcart's src/jit.js, so the native hosts run
// the same runtime-code-generation host code as CartHost / CartHostWeb.
//   node scripts/gen-jit-js.mjs <wasmcart checkout>/src/jit.js
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

const src = process.argv[2];
if (!src) { console.error('usage: gen-jit-js.mjs <wasmcart>/src/jit.js'); process.exit(2); }
const body = readFileSync(src, 'utf8').replace(/^export /gm, '');
if (body.includes(')WCJS')) throw new Error('jit.js contains the raw-string delimiter');
const out = `// GENERATED by scripts/gen-jit-js.mjs from wasmcart's src/jit.js. Do not edit.
//
// WC_JIT_LIB_JS evaluates to { createJitImports, JIT_LIMITS, JIT_OFF_NOTICE }:
// the host side of runtime code generation (wasmcart SPEC.md, "Runtime code
// generation"), shared verbatim with the JS hosts.
#ifndef WC_JIT_JS_H
#define WC_JIT_JS_H
static const char WC_JIT_LIB_JS[] = R"WCJS((function () {
'use strict';
${body}
return { createJitImports, JIT_LIMITS, JIT_OFF_NOTICE };
})())WCJS";
#endif
`;
const dest = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'jit_js.h');
writeFileSync(dest, out);
console.log(`wrote ${dest} (${out.length} bytes)`);
